// src/components/ui/CardGrid.tsx
import { FC } from 'react';
import { useSelector } from 'react-redux';
import { ICityWeather } from '../../types';
import { selectWeatherList, selectCityImages, selectStatus } from '../../features/weather/weather-slice';
import { CardCity, CardCitySkeleton } from './';

export const CardGrid: FC = () => {
  const citiesList = useSelector(selectWeatherList);
  const status = useSelector(selectStatus);
  const images = useSelector(selectCityImages);

  return (
    <div className="w-full max-w-screen-2xl m-auto grid grid-cols-1 gap-4 mt-20 lg:grid-cols-2 lg:gap-8 xl:grid-cols-3 xl:gap-8">
      {citiesList.map((city: ICityWeather) => {
        return (
          <CardCity
            key={city.id}
            city={city}
            image={images[city.id]}
          />
        );
      })}
      {status === 'loading' && <CardCitySkeleton />}
    </div>
  );
};

CardGrid.displayName = 'CardGrid';

// src/components/ui/CardGrid.vue
<template>
  <div class="w-full max-w-screen-2xl m-auto grid grid-cols-1 gap-4 mt-20 lg:grid-cols-2 lg:gap-8 xl:grid-cols-3 xl:gap-8">
    <CardCity
      v-for="city in weatherStore.getCities"
      :key="city.id"
      :city="city"
      :image="weatherStore.getImages[city.id] ? weatherStore.getImages[city.id] : ''"
    />

    <CardCitySkeleton />
  </div>
</template>

<script setup lang="ts">
import { useWeatherStore } from '@/stores/weather';
import CardCity from '@/components/ui/CardCity.vue';
import CardCitySkeleton from '@/components/ui/CardCitySkeleton.vue';

const weatherStore = useWeatherStore();
</script>
