// src/components/ui/SearchBar.tsx
import { FC, useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { MdOutlineLocationOff } from 'react-icons/md';
import { RiLoaderLine } from 'react-icons/ri';
import { toast } from 'react-toastify';
import { ISearchSuggestItem } from '../../types';
import { AppDispatch } from '../../store';
import { useDebounce } from '../../hooks';
import { getSearchCities, getCityData, selectCitiesSuggestions, weatherActions } from '../../features/weather/weather-slice';
import { SearchInput, SearchItem } from './';

export const SearchBar: FC = () => {
  const dispatch = useDispatch<AppDispatch>();
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [isSearching, setIsSearching] = useState<boolean>(false);
  const searchCitiesList = useSelector(selectCitiesSuggestions);
  const debouncedSearch = useDebounce(searchQuery, 1100);

  useEffect(() => {
    setIsSearching(true);

    if (searchQuery.length === 0) {
      dispatch(weatherActions.setCitiesSuggestions([]));
      setIsSearching(false);
    }
  }, [searchQuery]);

  useEffect(() => {
    if (debouncedSearch) {
      dispatch(getSearchCities(searchQuery))
        .unwrap()
        .then(() => {
          setIsSearching(false);
        })
        .catch((error) => {
          toast.error(error.message, {
            toastId: 'getSearchCitiesError'
          });
        });
    }
  }, [debouncedSearch]);

  function selectItemHandler(item: ISearchSuggestItem) {
    dispatch(getCityData(item))
      .unwrap()
      .then(() => {
        toast.success(`${item.name} city successfully added`, {
          theme: 'light',
          toastId: 'getCityDataSuccess'
        });
      })
      .catch((error) => {
        toast.error(error.message, {
          toastId: 'getCityDataError'
        });
      });
    setSearchQuery('');
  }

  function render() {
    if (isSearching && searchQuery.length !== 0) {
      return (
        <div className="flex items-center justify-center p-3">
          <div className="animate-spin">
            <RiLoaderLine className="w-6 h-6 opacity-30" />
          </div>
        </div>
      );
    }

    if (!isSearching && searchCitiesList.length === 0 && searchQuery.length !== 0) {
      return (
        <div className="flex items-center justify-center p-3 select-none">
          <MdOutlineLocationOff className="w-6 h-6 mr-3 opacity-30" />
          <p className="text-xl">City not found</p>
        </div>
      );
    }

    return searchCitiesList.map((city: ISearchSuggestItem) => {
      return (
        <SearchItem
          key={city.id}
          city={city}
          onSelectItem={selectItemHandler}
        />
      );
    });
  }

  return (
    <>
      <div className="relative">
        <SearchInput
          id="city_search"
          type="text"
          label="Search"
          placeholder="Start typing city name..."
          value={searchQuery}
          onChange={(value) => setSearchQuery(value)}
          autoComplete="off"
        />
        <div className="absolute left-0 top-full w-full bg-gray-100 rounded-xl z-50 shadow-sm shadow-gray-200 overflow-hidden">
          {render()}
        </div>
      </div>
    </>
  );
};

SearchBar.displayName = 'SearchBar';

// src/components/ui/SearchBar.vue
<template>
  <div class="relative">
    <SearchInput
      id="city_search"
      type="text"
      label="Search"
      placeholder="Start typing city name..."
      autoComplete="off"
      v-model="searchQuery"
    />

    <div class="absolute left-0 top-full w-full bg-gray-100 rounded-xl z-50 shadow-sm shadow-gray-200 overflow-hidden">
      <div
        v-if="!isSearching && citiesSuggestions.length === 0 && searchQuery.length !== 0"
        class="flex items-center justify-center w-full p-3 select-none"
      >
        <v-icon name="md-locationoff-twotone" class="w-6 h-6 mr-3 opacity-30"/>
        <div class="text-xl overflow-hidden">
          <p class="text-xl">City not found</p>
        </div>
      </div>

      <div
        v-else-if="isSearching && searchQuery.length !== 0"
        class="flex items-center justify-center w-full p-3"
      >
        <div class="animate-spin">
          <v-icon name="ri-loader-line" class="w-6 h-6 opacity-30" />
        </div>
      </div>

      <template v-else>
        <SearchSuggestionItem
          v-for="item in citiesSuggestions"
          :key="item.id"
          :name="item.name"
          :country="item.country"
          @click="getCityWeather(item)"
        />
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { ISearchSuggestItem } from '@/types';
import { watchDebounced } from '@vueuse/core';
import { useCommonStore, useWeatherStore } from '@/stores';
import { suggestionsCitiesService } from '@/services';
import SearchInput from '@/components/ui/SearchInput.vue';
import SearchSuggestionItem from '@/components/ui/SearchSuggestionItem.vue';

const commonStore = useCommonStore();
const weatherStore = useWeatherStore();
const searchQuery = ref('');
const citiesSuggestions = ref([]);
const isSearching = ref(false);

watch(searchQuery, () => {
  if (searchQuery.value.length === 0) {
    citiesSuggestions.value = [];
    isSearching.value = false;

    return;
  }

  isSearching.value = true;
});

watchDebounced(searchQuery, async () => {
  await suggestionsCitiesService(searchQuery.value)
    .then((suggestionList) => {
      if (suggestionList.length > 0) {
        citiesSuggestions.value = suggestionList.filter((city) => {
          return !weatherStore.getIds.includes(city.id);
        });

        commonStore.setStatus('success');
        isSearching.value = false;
      } else {
        isSearching.value = false;
        commonStore.setStatus('init');
      }
    })
    .catch((error) => {
      commonStore.setStatus('error');
      commonStore.setErrorMessage(error.message);
    });
}, { debounce: 1100, maxWait: 5000 });

function getCityWeather(suggestionItem: ISearchSuggestItem) {
  isSearching.value = false;
  searchQuery.value = '';
  citiesSuggestions.value = [];

  weatherStore.getCityData(suggestionItem);
}
</script>
